install:
	mvn clean install

compile:
	mvn clean compile

server:
	mvn exec:java -Dexec.mainClass="project.Server"

client:
	mvn exec:java -Dexec.mainClass="project.ClientKt"

javadoc:
	mvn javadoc:javadoc

dokka:
	mvn dokka:javadoc
