initServer:
	java src.TCPServer

initClient:
	java src.TCPClient

compile:
	javac src/TCPServer.java src/TCPClient.java src/tools/*.java

clear:
	rm -f src/TCPClient.class src/TCPServer.class src/tools/ReceiveThread.class src/tools/SendThread.class