// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/project/Movie.proto

package project.javaOut.output;

public final class MovieWrapper {
  private MovieWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Movie_Movie_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Movie_Movie_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Movie_Actor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Movie_Actor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/java/project/Movie.proto\022\005Mov" +
      "ie\"1\n\005Movie\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\016\n" +
      "\006rating\030\003 \001(\005\"\"\n\005Actor\022\014\n\004name\030\001 \001(\t\022\013\n\003" +
      "age\030\002 \001(\005B\030\n\006outputB\014MovieWrapperP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Movie_Movie_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Movie_Movie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Movie_Movie_descriptor,
        new java.lang.String[] { "Name", "Id", "Rating", });
    internal_static_Movie_Actor_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Movie_Actor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Movie_Actor_descriptor,
        new java.lang.String[] { "Name", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
