// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/project/Movie.proto

package project.javaOut;

/**
 * Protobuf type {@code Movie.Movie}
 */
public final class Movie extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Movie.Movie)
    MovieOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Movie.newBuilder() to construct.
  private Movie(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Movie() {
    title_ = "";
    released_ = "";
    poster_ = "";
    plot_ = "";
    fullplot_ = "";
    directors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    cast_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    contries_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    genres_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Movie();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return project.javaOut.MovieWrapper.internal_static_Movie_Movie_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return project.javaOut.MovieWrapper.internal_static_Movie_Movie_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            project.javaOut.Movie.class, project.javaOut.Movie.Builder.class);
  }

  private int bitField0_;
  public static final int TITLE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>required string title = 1;</code>
   * @return Whether the title field is set.
   */
  @java.lang.Override
  public boolean hasTitle() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string title = 1;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        title_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string title = 1;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int YEAR_FIELD_NUMBER = 2;
  private int year_ = 0;
  /**
   * <code>optional int32 year = 2;</code>
   * @return Whether the year field is set.
   */
  @java.lang.Override
  public boolean hasYear() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 year = 2;</code>
   * @return The year.
   */
  @java.lang.Override
  public int getYear() {
    return year_;
  }

  public static final int RELEASED_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object released_ = "";
  /**
   * <code>optional string released = 3;</code>
   * @return Whether the released field is set.
   */
  @java.lang.Override
  public boolean hasReleased() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string released = 3;</code>
   * @return The released.
   */
  @java.lang.Override
  public java.lang.String getReleased() {
    java.lang.Object ref = released_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        released_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string released = 3;</code>
   * @return The bytes for released.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReleasedBytes() {
    java.lang.Object ref = released_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      released_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSTER_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object poster_ = "";
  /**
   * <code>optional string poster = 4;</code>
   * @return Whether the poster field is set.
   */
  @java.lang.Override
  public boolean hasPoster() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string poster = 4;</code>
   * @return The poster.
   */
  @java.lang.Override
  public java.lang.String getPoster() {
    java.lang.Object ref = poster_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        poster_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string poster = 4;</code>
   * @return The bytes for poster.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPosterBytes() {
    java.lang.Object ref = poster_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      poster_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLOT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object plot_ = "";
  /**
   * <code>optional string plot = 5;</code>
   * @return Whether the plot field is set.
   */
  @java.lang.Override
  public boolean hasPlot() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string plot = 5;</code>
   * @return The plot.
   */
  @java.lang.Override
  public java.lang.String getPlot() {
    java.lang.Object ref = plot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        plot_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string plot = 5;</code>
   * @return The bytes for plot.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlotBytes() {
    java.lang.Object ref = plot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      plot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FULLPLOT_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fullplot_ = "";
  /**
   * <code>optional string fullplot = 6;</code>
   * @return Whether the fullplot field is set.
   */
  @java.lang.Override
  public boolean hasFullplot() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string fullplot = 6;</code>
   * @return The fullplot.
   */
  @java.lang.Override
  public java.lang.String getFullplot() {
    java.lang.Object ref = fullplot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        fullplot_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string fullplot = 6;</code>
   * @return The bytes for fullplot.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFullplotBytes() {
    java.lang.Object ref = fullplot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fullplot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIRECTORS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList directors_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string directors = 7;</code>
   * @return A list containing the directors.
   */
  public com.google.protobuf.ProtocolStringList
      getDirectorsList() {
    return directors_;
  }
  /**
   * <code>repeated string directors = 7;</code>
   * @return The count of directors.
   */
  public int getDirectorsCount() {
    return directors_.size();
  }
  /**
   * <code>repeated string directors = 7;</code>
   * @param index The index of the element to return.
   * @return The directors at the given index.
   */
  public java.lang.String getDirectors(int index) {
    return directors_.get(index);
  }
  /**
   * <code>repeated string directors = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the directors at the given index.
   */
  public com.google.protobuf.ByteString
      getDirectorsBytes(int index) {
    return directors_.getByteString(index);
  }

  public static final int CAST_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList cast_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string cast = 8;</code>
   * @return A list containing the cast.
   */
  public com.google.protobuf.ProtocolStringList
      getCastList() {
    return cast_;
  }
  /**
   * <code>repeated string cast = 8;</code>
   * @return The count of cast.
   */
  public int getCastCount() {
    return cast_.size();
  }
  /**
   * <code>repeated string cast = 8;</code>
   * @param index The index of the element to return.
   * @return The cast at the given index.
   */
  public java.lang.String getCast(int index) {
    return cast_.get(index);
  }
  /**
   * <code>repeated string cast = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the cast at the given index.
   */
  public com.google.protobuf.ByteString
      getCastBytes(int index) {
    return cast_.getByteString(index);
  }

  public static final int CONTRIES_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList contries_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string contries = 9;</code>
   * @return A list containing the contries.
   */
  public com.google.protobuf.ProtocolStringList
      getContriesList() {
    return contries_;
  }
  /**
   * <code>repeated string contries = 9;</code>
   * @return The count of contries.
   */
  public int getContriesCount() {
    return contries_.size();
  }
  /**
   * <code>repeated string contries = 9;</code>
   * @param index The index of the element to return.
   * @return The contries at the given index.
   */
  public java.lang.String getContries(int index) {
    return contries_.get(index);
  }
  /**
   * <code>repeated string contries = 9;</code>
   * @param index The index of the value to return.
   * @return The bytes of the contries at the given index.
   */
  public com.google.protobuf.ByteString
      getContriesBytes(int index) {
    return contries_.getByteString(index);
  }

  public static final int GENRES_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList genres_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string genres = 10;</code>
   * @return A list containing the genres.
   */
  public com.google.protobuf.ProtocolStringList
      getGenresList() {
    return genres_;
  }
  /**
   * <code>repeated string genres = 10;</code>
   * @return The count of genres.
   */
  public int getGenresCount() {
    return genres_.size();
  }
  /**
   * <code>repeated string genres = 10;</code>
   * @param index The index of the element to return.
   * @return The genres at the given index.
   */
  public java.lang.String getGenres(int index) {
    return genres_.get(index);
  }
  /**
   * <code>repeated string genres = 10;</code>
   * @param index The index of the value to return.
   * @return The bytes of the genres at the given index.
   */
  public com.google.protobuf.ByteString
      getGenresBytes(int index) {
    return genres_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasTitle()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, year_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, released_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, poster_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, plot_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, fullplot_);
    }
    for (int i = 0; i < directors_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, directors_.getRaw(i));
    }
    for (int i = 0; i < cast_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, cast_.getRaw(i));
    }
    for (int i = 0; i < contries_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, contries_.getRaw(i));
    }
    for (int i = 0; i < genres_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, genres_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, year_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, released_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, poster_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, plot_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, fullplot_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < directors_.size(); i++) {
        dataSize += computeStringSizeNoTag(directors_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDirectorsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < cast_.size(); i++) {
        dataSize += computeStringSizeNoTag(cast_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCastList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < contries_.size(); i++) {
        dataSize += computeStringSizeNoTag(contries_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getContriesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < genres_.size(); i++) {
        dataSize += computeStringSizeNoTag(genres_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getGenresList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof project.javaOut.Movie)) {
      return super.equals(obj);
    }
    project.javaOut.Movie other = (project.javaOut.Movie) obj;

    if (hasTitle() != other.hasTitle()) return false;
    if (hasTitle()) {
      if (!getTitle()
          .equals(other.getTitle())) return false;
    }
    if (hasYear() != other.hasYear()) return false;
    if (hasYear()) {
      if (getYear()
          != other.getYear()) return false;
    }
    if (hasReleased() != other.hasReleased()) return false;
    if (hasReleased()) {
      if (!getReleased()
          .equals(other.getReleased())) return false;
    }
    if (hasPoster() != other.hasPoster()) return false;
    if (hasPoster()) {
      if (!getPoster()
          .equals(other.getPoster())) return false;
    }
    if (hasPlot() != other.hasPlot()) return false;
    if (hasPlot()) {
      if (!getPlot()
          .equals(other.getPlot())) return false;
    }
    if (hasFullplot() != other.hasFullplot()) return false;
    if (hasFullplot()) {
      if (!getFullplot()
          .equals(other.getFullplot())) return false;
    }
    if (!getDirectorsList()
        .equals(other.getDirectorsList())) return false;
    if (!getCastList()
        .equals(other.getCastList())) return false;
    if (!getContriesList()
        .equals(other.getContriesList())) return false;
    if (!getGenresList()
        .equals(other.getGenresList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTitle()) {
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
    }
    if (hasYear()) {
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
    }
    if (hasReleased()) {
      hash = (37 * hash) + RELEASED_FIELD_NUMBER;
      hash = (53 * hash) + getReleased().hashCode();
    }
    if (hasPoster()) {
      hash = (37 * hash) + POSTER_FIELD_NUMBER;
      hash = (53 * hash) + getPoster().hashCode();
    }
    if (hasPlot()) {
      hash = (37 * hash) + PLOT_FIELD_NUMBER;
      hash = (53 * hash) + getPlot().hashCode();
    }
    if (hasFullplot()) {
      hash = (37 * hash) + FULLPLOT_FIELD_NUMBER;
      hash = (53 * hash) + getFullplot().hashCode();
    }
    if (getDirectorsCount() > 0) {
      hash = (37 * hash) + DIRECTORS_FIELD_NUMBER;
      hash = (53 * hash) + getDirectorsList().hashCode();
    }
    if (getCastCount() > 0) {
      hash = (37 * hash) + CAST_FIELD_NUMBER;
      hash = (53 * hash) + getCastList().hashCode();
    }
    if (getContriesCount() > 0) {
      hash = (37 * hash) + CONTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getContriesList().hashCode();
    }
    if (getGenresCount() > 0) {
      hash = (37 * hash) + GENRES_FIELD_NUMBER;
      hash = (53 * hash) + getGenresList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static project.javaOut.Movie parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static project.javaOut.Movie parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static project.javaOut.Movie parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static project.javaOut.Movie parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static project.javaOut.Movie parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static project.javaOut.Movie parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static project.javaOut.Movie parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static project.javaOut.Movie parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static project.javaOut.Movie parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static project.javaOut.Movie parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static project.javaOut.Movie parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static project.javaOut.Movie parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(project.javaOut.Movie prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Movie.Movie}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Movie.Movie)
      project.javaOut.MovieOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return project.javaOut.MovieWrapper.internal_static_Movie_Movie_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return project.javaOut.MovieWrapper.internal_static_Movie_Movie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              project.javaOut.Movie.class, project.javaOut.Movie.Builder.class);
    }

    // Construct using project.javaOut.Movie.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      title_ = "";
      year_ = 0;
      released_ = "";
      poster_ = "";
      plot_ = "";
      fullplot_ = "";
      directors_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      cast_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      contries_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      genres_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return project.javaOut.MovieWrapper.internal_static_Movie_Movie_descriptor;
    }

    @java.lang.Override
    public project.javaOut.Movie getDefaultInstanceForType() {
      return project.javaOut.Movie.getDefaultInstance();
    }

    @java.lang.Override
    public project.javaOut.Movie build() {
      project.javaOut.Movie result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public project.javaOut.Movie buildPartial() {
      project.javaOut.Movie result = new project.javaOut.Movie(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(project.javaOut.Movie result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.title_ = title_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.year_ = year_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.released_ = released_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.poster_ = poster_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.plot_ = plot_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.fullplot_ = fullplot_;
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        directors_.makeImmutable();
        result.directors_ = directors_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        cast_.makeImmutable();
        result.cast_ = cast_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        contries_.makeImmutable();
        result.contries_ = contries_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        genres_.makeImmutable();
        result.genres_ = genres_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof project.javaOut.Movie) {
        return mergeFrom((project.javaOut.Movie)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(project.javaOut.Movie other) {
      if (other == project.javaOut.Movie.getDefaultInstance()) return this;
      if (other.hasTitle()) {
        title_ = other.title_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasYear()) {
        setYear(other.getYear());
      }
      if (other.hasReleased()) {
        released_ = other.released_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasPoster()) {
        poster_ = other.poster_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasPlot()) {
        plot_ = other.plot_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasFullplot()) {
        fullplot_ = other.fullplot_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.directors_.isEmpty()) {
        if (directors_.isEmpty()) {
          directors_ = other.directors_;
          bitField0_ |= 0x00000040;
        } else {
          ensureDirectorsIsMutable();
          directors_.addAll(other.directors_);
        }
        onChanged();
      }
      if (!other.cast_.isEmpty()) {
        if (cast_.isEmpty()) {
          cast_ = other.cast_;
          bitField0_ |= 0x00000080;
        } else {
          ensureCastIsMutable();
          cast_.addAll(other.cast_);
        }
        onChanged();
      }
      if (!other.contries_.isEmpty()) {
        if (contries_.isEmpty()) {
          contries_ = other.contries_;
          bitField0_ |= 0x00000100;
        } else {
          ensureContriesIsMutable();
          contries_.addAll(other.contries_);
        }
        onChanged();
      }
      if (!other.genres_.isEmpty()) {
        if (genres_.isEmpty()) {
          genres_ = other.genres_;
          bitField0_ |= 0x00000200;
        } else {
          ensureGenresIsMutable();
          genres_.addAll(other.genres_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasTitle()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              title_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              year_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              released_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              poster_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              plot_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              fullplot_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              ensureDirectorsIsMutable();
              directors_.add(bs);
              break;
            } // case 58
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              ensureCastIsMutable();
              cast_.add(bs);
              break;
            } // case 66
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              ensureContriesIsMutable();
              contries_.add(bs);
              break;
            } // case 74
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              ensureGenresIsMutable();
              genres_.add(bs);
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object title_ = "";
    /**
     * <code>required string title = 1;</code>
     * @return Whether the title field is set.
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string title = 1;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string title = 1;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string title = 1;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>required string title = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>required string title = 1;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int year_ ;
    /**
     * <code>optional int32 year = 2;</code>
     * @return Whether the year field is set.
     */
    @java.lang.Override
    public boolean hasYear() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 year = 2;</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }
    /**
     * <code>optional int32 year = 2;</code>
     * @param value The year to set.
     * @return This builder for chaining.
     */
    public Builder setYear(int value) {

      year_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 year = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearYear() {
      bitField0_ = (bitField0_ & ~0x00000002);
      year_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object released_ = "";
    /**
     * <code>optional string released = 3;</code>
     * @return Whether the released field is set.
     */
    public boolean hasReleased() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string released = 3;</code>
     * @return The released.
     */
    public java.lang.String getReleased() {
      java.lang.Object ref = released_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          released_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string released = 3;</code>
     * @return The bytes for released.
     */
    public com.google.protobuf.ByteString
        getReleasedBytes() {
      java.lang.Object ref = released_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        released_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string released = 3;</code>
     * @param value The released to set.
     * @return This builder for chaining.
     */
    public Builder setReleased(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      released_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string released = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReleased() {
      released_ = getDefaultInstance().getReleased();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string released = 3;</code>
     * @param value The bytes for released to set.
     * @return This builder for chaining.
     */
    public Builder setReleasedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      released_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object poster_ = "";
    /**
     * <code>optional string poster = 4;</code>
     * @return Whether the poster field is set.
     */
    public boolean hasPoster() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string poster = 4;</code>
     * @return The poster.
     */
    public java.lang.String getPoster() {
      java.lang.Object ref = poster_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          poster_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string poster = 4;</code>
     * @return The bytes for poster.
     */
    public com.google.protobuf.ByteString
        getPosterBytes() {
      java.lang.Object ref = poster_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        poster_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string poster = 4;</code>
     * @param value The poster to set.
     * @return This builder for chaining.
     */
    public Builder setPoster(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      poster_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string poster = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPoster() {
      poster_ = getDefaultInstance().getPoster();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string poster = 4;</code>
     * @param value The bytes for poster to set.
     * @return This builder for chaining.
     */
    public Builder setPosterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      poster_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object plot_ = "";
    /**
     * <code>optional string plot = 5;</code>
     * @return Whether the plot field is set.
     */
    public boolean hasPlot() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string plot = 5;</code>
     * @return The plot.
     */
    public java.lang.String getPlot() {
      java.lang.Object ref = plot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          plot_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string plot = 5;</code>
     * @return The bytes for plot.
     */
    public com.google.protobuf.ByteString
        getPlotBytes() {
      java.lang.Object ref = plot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        plot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string plot = 5;</code>
     * @param value The plot to set.
     * @return This builder for chaining.
     */
    public Builder setPlot(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      plot_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional string plot = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlot() {
      plot_ = getDefaultInstance().getPlot();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>optional string plot = 5;</code>
     * @param value The bytes for plot to set.
     * @return This builder for chaining.
     */
    public Builder setPlotBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      plot_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object fullplot_ = "";
    /**
     * <code>optional string fullplot = 6;</code>
     * @return Whether the fullplot field is set.
     */
    public boolean hasFullplot() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string fullplot = 6;</code>
     * @return The fullplot.
     */
    public java.lang.String getFullplot() {
      java.lang.Object ref = fullplot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fullplot_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string fullplot = 6;</code>
     * @return The bytes for fullplot.
     */
    public com.google.protobuf.ByteString
        getFullplotBytes() {
      java.lang.Object ref = fullplot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullplot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string fullplot = 6;</code>
     * @param value The fullplot to set.
     * @return This builder for chaining.
     */
    public Builder setFullplot(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fullplot_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional string fullplot = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFullplot() {
      fullplot_ = getDefaultInstance().getFullplot();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>optional string fullplot = 6;</code>
     * @param value The bytes for fullplot to set.
     * @return This builder for chaining.
     */
    public Builder setFullplotBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      fullplot_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList directors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureDirectorsIsMutable() {
      if (!directors_.isModifiable()) {
        directors_ = new com.google.protobuf.LazyStringArrayList(directors_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <code>repeated string directors = 7;</code>
     * @return A list containing the directors.
     */
    public com.google.protobuf.ProtocolStringList
        getDirectorsList() {
      directors_.makeImmutable();
      return directors_;
    }
    /**
     * <code>repeated string directors = 7;</code>
     * @return The count of directors.
     */
    public int getDirectorsCount() {
      return directors_.size();
    }
    /**
     * <code>repeated string directors = 7;</code>
     * @param index The index of the element to return.
     * @return The directors at the given index.
     */
    public java.lang.String getDirectors(int index) {
      return directors_.get(index);
    }
    /**
     * <code>repeated string directors = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the directors at the given index.
     */
    public com.google.protobuf.ByteString
        getDirectorsBytes(int index) {
      return directors_.getByteString(index);
    }
    /**
     * <code>repeated string directors = 7;</code>
     * @param index The index to set the value at.
     * @param value The directors to set.
     * @return This builder for chaining.
     */
    public Builder setDirectors(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDirectorsIsMutable();
      directors_.set(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directors = 7;</code>
     * @param value The directors to add.
     * @return This builder for chaining.
     */
    public Builder addDirectors(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDirectorsIsMutable();
      directors_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directors = 7;</code>
     * @param values The directors to add.
     * @return This builder for chaining.
     */
    public Builder addAllDirectors(
        java.lang.Iterable<java.lang.String> values) {
      ensureDirectorsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, directors_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directors = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirectors() {
      directors_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string directors = 7;</code>
     * @param value The bytes of the directors to add.
     * @return This builder for chaining.
     */
    public Builder addDirectorsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDirectorsIsMutable();
      directors_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList cast_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureCastIsMutable() {
      if (!cast_.isModifiable()) {
        cast_ = new com.google.protobuf.LazyStringArrayList(cast_);
      }
      bitField0_ |= 0x00000080;
    }
    /**
     * <code>repeated string cast = 8;</code>
     * @return A list containing the cast.
     */
    public com.google.protobuf.ProtocolStringList
        getCastList() {
      cast_.makeImmutable();
      return cast_;
    }
    /**
     * <code>repeated string cast = 8;</code>
     * @return The count of cast.
     */
    public int getCastCount() {
      return cast_.size();
    }
    /**
     * <code>repeated string cast = 8;</code>
     * @param index The index of the element to return.
     * @return The cast at the given index.
     */
    public java.lang.String getCast(int index) {
      return cast_.get(index);
    }
    /**
     * <code>repeated string cast = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the cast at the given index.
     */
    public com.google.protobuf.ByteString
        getCastBytes(int index) {
      return cast_.getByteString(index);
    }
    /**
     * <code>repeated string cast = 8;</code>
     * @param index The index to set the value at.
     * @param value The cast to set.
     * @return This builder for chaining.
     */
    public Builder setCast(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCastIsMutable();
      cast_.set(index, value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cast = 8;</code>
     * @param value The cast to add.
     * @return This builder for chaining.
     */
    public Builder addCast(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCastIsMutable();
      cast_.add(value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cast = 8;</code>
     * @param values The cast to add.
     * @return This builder for chaining.
     */
    public Builder addAllCast(
        java.lang.Iterable<java.lang.String> values) {
      ensureCastIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, cast_);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cast = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCast() {
      cast_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000080);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string cast = 8;</code>
     * @param value The bytes of the cast to add.
     * @return This builder for chaining.
     */
    public Builder addCastBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureCastIsMutable();
      cast_.add(value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList contries_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureContriesIsMutable() {
      if (!contries_.isModifiable()) {
        contries_ = new com.google.protobuf.LazyStringArrayList(contries_);
      }
      bitField0_ |= 0x00000100;
    }
    /**
     * <code>repeated string contries = 9;</code>
     * @return A list containing the contries.
     */
    public com.google.protobuf.ProtocolStringList
        getContriesList() {
      contries_.makeImmutable();
      return contries_;
    }
    /**
     * <code>repeated string contries = 9;</code>
     * @return The count of contries.
     */
    public int getContriesCount() {
      return contries_.size();
    }
    /**
     * <code>repeated string contries = 9;</code>
     * @param index The index of the element to return.
     * @return The contries at the given index.
     */
    public java.lang.String getContries(int index) {
      return contries_.get(index);
    }
    /**
     * <code>repeated string contries = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the contries at the given index.
     */
    public com.google.protobuf.ByteString
        getContriesBytes(int index) {
      return contries_.getByteString(index);
    }
    /**
     * <code>repeated string contries = 9;</code>
     * @param index The index to set the value at.
     * @param value The contries to set.
     * @return This builder for chaining.
     */
    public Builder setContries(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureContriesIsMutable();
      contries_.set(index, value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string contries = 9;</code>
     * @param value The contries to add.
     * @return This builder for chaining.
     */
    public Builder addContries(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureContriesIsMutable();
      contries_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string contries = 9;</code>
     * @param values The contries to add.
     * @return This builder for chaining.
     */
    public Builder addAllContries(
        java.lang.Iterable<java.lang.String> values) {
      ensureContriesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, contries_);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string contries = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearContries() {
      contries_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000100);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string contries = 9;</code>
     * @param value The bytes of the contries to add.
     * @return This builder for chaining.
     */
    public Builder addContriesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureContriesIsMutable();
      contries_.add(value);
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList genres_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureGenresIsMutable() {
      if (!genres_.isModifiable()) {
        genres_ = new com.google.protobuf.LazyStringArrayList(genres_);
      }
      bitField0_ |= 0x00000200;
    }
    /**
     * <code>repeated string genres = 10;</code>
     * @return A list containing the genres.
     */
    public com.google.protobuf.ProtocolStringList
        getGenresList() {
      genres_.makeImmutable();
      return genres_;
    }
    /**
     * <code>repeated string genres = 10;</code>
     * @return The count of genres.
     */
    public int getGenresCount() {
      return genres_.size();
    }
    /**
     * <code>repeated string genres = 10;</code>
     * @param index The index of the element to return.
     * @return The genres at the given index.
     */
    public java.lang.String getGenres(int index) {
      return genres_.get(index);
    }
    /**
     * <code>repeated string genres = 10;</code>
     * @param index The index of the value to return.
     * @return The bytes of the genres at the given index.
     */
    public com.google.protobuf.ByteString
        getGenresBytes(int index) {
      return genres_.getByteString(index);
    }
    /**
     * <code>repeated string genres = 10;</code>
     * @param index The index to set the value at.
     * @param value The genres to set.
     * @return This builder for chaining.
     */
    public Builder setGenres(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureGenresIsMutable();
      genres_.set(index, value);
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string genres = 10;</code>
     * @param value The genres to add.
     * @return This builder for chaining.
     */
    public Builder addGenres(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureGenresIsMutable();
      genres_.add(value);
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string genres = 10;</code>
     * @param values The genres to add.
     * @return This builder for chaining.
     */
    public Builder addAllGenres(
        java.lang.Iterable<java.lang.String> values) {
      ensureGenresIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, genres_);
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string genres = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearGenres() {
      genres_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000200);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string genres = 10;</code>
     * @param value The bytes of the genres to add.
     * @return This builder for chaining.
     */
    public Builder addGenresBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureGenresIsMutable();
      genres_.add(value);
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Movie.Movie)
  }

  // @@protoc_insertion_point(class_scope:Movie.Movie)
  private static final project.javaOut.Movie DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new project.javaOut.Movie();
  }

  public static project.javaOut.Movie getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Movie>
      PARSER = new com.google.protobuf.AbstractParser<Movie>() {
    @java.lang.Override
    public Movie parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Movie> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Movie> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public project.javaOut.Movie getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

