// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/project/Movie.proto

package project.javaOut;

public final class MovieWrapper {
  private MovieWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Movie_Movie_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Movie_Movie_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/java/project/Movie.proto\022\005Mov" +
      "ie\"\251\001\n\005Movie\022\r\n\005title\030\001 \002(\t\022\014\n\004year\030\002 \001(" +
      "\005\022\020\n\010released\030\003 \001(\t\022\016\n\006poster\030\004 \001(\t\022\014\n\004p" +
      "lot\030\005 \001(\t\022\020\n\010fullplot\030\006 \001(\t\022\021\n\tdirectors" +
      "\030\007 \003(\t\022\014\n\004cast\030\010 \003(\t\022\020\n\010contries\030\t \003(\t\022\016" +
      "\n\006genres\030\n \003(\tB!\n\017project.javaOutB\014Movie" +
      "WrapperP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Movie_Movie_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Movie_Movie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Movie_Movie_descriptor,
        new java.lang.String[] { "Title", "Year", "Released", "Poster", "Plot", "Fullplot", "Directors", "Cast", "Contries", "Genres", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
