// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/java/Movie.proto

package src.java;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:movie.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .movie.Person people = 1;</code>
   */
  java.util.List<src.java.Person> 
      getPeopleList();
  /**
   * <code>repeated .movie.Person people = 1;</code>
   */
  src.java.Person getPeople(int index);
  /**
   * <code>repeated .movie.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .movie.Person people = 1;</code>
   */
  java.util.List<? extends src.java.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .movie.Person people = 1;</code>
   */
  src.java.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
