outputJava:
	protoc --java_out=./src/main/java/project/javaOut/ ./src/main/java/project/Movie.proto

outputKotlin:
	protoc --kotlin_out=./src/main/java/project/kotlinOut/ ./src/main/java/project/Movie.proto

clearOutputs:
	rm -rf ./src/main/java/project/javaOut/output
	rm -rf ./src/main/java/project/kotlinOut/output

