install:
	mvn clean install

compile:
	mvn clean compile

publisher:
	mvn exec:java -Dexec.mainClass="project.Publisher"

consumer:
	mvn exec:java -Dexec.mainClass="project.Consumer"

javadoc:
	mvn javadoc:javadoc

dokka:
	mvn dokka:javadoc
