// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/java/project/Movie.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package output;

@kotlin.jvm.JvmName("-initializemovie")
public inline fun movie(block: output.MovieKt.Dsl.() -> kotlin.Unit): output.Movie =
  output.MovieKt.Dsl._create(output.Movie.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `Movie.Movie`
 */
public object MovieKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: output.Movie.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: output.Movie.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): output.Movie = _builder.build()

    /**
     * `optional string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `optional string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }
    /**
     * `optional string name = 1;`
     * @return Whether the name field is set.
     */
    public fun hasName(): kotlin.Boolean {
      return _builder.hasName()
    }

    /**
     * `optional int32 id = 2;`
     */
    public var id: kotlin.Int
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `optional int32 id = 2;`
     */
    public fun clearId() {
      _builder.clearId()
    }
    /**
     * `optional int32 id = 2;`
     * @return Whether the id field is set.
     */
    public fun hasId(): kotlin.Boolean {
      return _builder.hasId()
    }

    /**
     * `optional int32 rating = 3;`
     */
    public var rating: kotlin.Int
      @JvmName("getRating")
      get() = _builder.getRating()
      @JvmName("setRating")
      set(value) {
        _builder.setRating(value)
      }
    /**
     * `optional int32 rating = 3;`
     */
    public fun clearRating() {
      _builder.clearRating()
    }
    /**
     * `optional int32 rating = 3;`
     * @return Whether the rating field is set.
     */
    public fun hasRating(): kotlin.Boolean {
      return _builder.hasRating()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun output.Movie.copy(block: output.MovieKt.Dsl.() -> kotlin.Unit): output.Movie =
  output.MovieKt.Dsl._create(this.toBuilder()).apply { block() }._build()

