// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: src/main/java/project/Movie.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package output;

